import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
async function api(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('Content-Type','application/json');const t=localStorage.getItem('dhat_admin_token');if(t)h.set('Authorization',`Bearer ${t}`);const r=await fetch(API+path,{...init,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'فشل الطلب');return d}
function App(){const[me,setMe]=useState<any>();const[data,setData]=useState<any>();const[audit,setAudit]=useState<any[]>([]);const[deposits,setDeposits]=useState<any[]>([]);const[msg,setMsg]=useState('');const[token,setToken]=useState(localStorage.getItem('dhat_admin_token')||'');
useEffect(()=>{if(token)api('/api/v1/auth/me').then(x=>{if(!['OWNER','ADMIN','FINANCE'].includes(x.role))throw Error('لا توجد صلاحية إدارية');setMe(x)}).catch(e=>{localStorage.removeItem('dhat_admin_token');setToken('');setMsg(e.message)})},[token]);
useEffect(()=>{if(me){api('/api/v1/admin/analytics').then(setData);api('/api/v1/admin/audit').then(setAudit)}},[me]);
async function approve(id:number){try{await api(`/api/v1/admin/deposits/${id}/approve`,{method:'POST'});setMsg('تم اعتماد الإيداع');}catch(e:any){setMsg(e.message)}}
if(!token)return <main dir="rtl"><h1>DHĀT ADMIN</h1><p>افتح لوحة الإدارة من Mini App/جلسة Telegram ثم ألصق Bearer token هنا فقط محليًا.</p><input value={token} onChange={e=>setToken(e.target.value)} placeholder="Session token"/><button onClick={()=>{localStorage.setItem('dhat_admin_token',token);setMe(null)}}>دخول</button>{msg&&<p>{msg}</p>}</main>;
return <main dir="rtl"><header><h1>لوحة تحكم DHĀT</h1><button onClick={()=>{localStorage.removeItem('dhat_admin_token');location.reload()}}>خروج</button></header>{msg&&<div className="notice">{msg}</div>}<div className="cards"><div>المستخدمون<strong>{data?.users??'—'}</strong></div><div>الطلبات<strong>{data?.orders??'—'}</strong></div><div>المكتملة<strong>{data?.completed_orders??'—'}</strong></div><div>الإيراد<strong>{data?.revenue??'—'}</strong></div></div><section><h2>سجل التدقيق</h2>{audit.map(x=><article key={x.id}><b>{x.action}</b><span>#{x.target}</span><small>{x.created_at}</small></article>)}</section><section><h2>الإيداعات</h2><p>اعتماد الإيداع يتم عبر endpoint محمي بالـRBAC ويدعم idempotency.</p><button onClick={async()=>{const d=await api('/api/v1/deposits');setDeposits(d)}}>تحديث</button>{deposits.map(x=><article key={x.id}><b>#{x.id}</b> {x.amount} {x.currency} — {x.status}{x.status==='PENDING'&&<button onClick={()=>approve(x.id)}>اعتماد</button>}</article>)}</section></main>}createRoot(document.getElementById('root')!).render(<App/>);
