from alembic import op
import sqlalchemy as sa
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('telegram_id',sa.BigInteger(),unique=True),sa.Column('username',sa.String(128)),sa.Column('role',sa.String(32),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('sessions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('token_hash',sa.String(64),unique=True,nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('revoked_at',sa.DateTime(timezone=True)),sa.Column('last_used_at',sa.DateTime(timezone=True),nullable=False))
    op.create_index('ix_sessions_token_hash','sessions',['token_hash'])
    op.create_table('categories',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('name',sa.String(160),unique=True,nullable=False),sa.Column('slug',sa.String(160),unique=True,nullable=False),sa.Column('enabled',sa.Boolean(),nullable=False))
    op.create_table('services',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('category_id',sa.Integer(),sa.ForeignKey('categories.id'),nullable=False),sa.Column('name',sa.String(200),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('price',sa.Numeric(18,4),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('stock',sa.Integer(),nullable=False),sa.Column('enabled',sa.Boolean(),nullable=False),sa.CheckConstraint('price >= 0'),sa.CheckConstraint('stock >= 0')))
    op.create_table('wallets',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('balance',sa.Numeric(20,4),nullable=False),sa.UniqueConstraint('user_id','currency'),sa.CheckConstraint('balance >= 0'))
    op.create_table('wallet_transactions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('wallet_id',sa.Integer(),sa.ForeignKey('wallets.id'),nullable=False),sa.Column('amount',sa.Numeric(20,4),nullable=False),sa.Column('type',sa.String(32),nullable=False),sa.Column('idempotency_key',sa.String(128),unique=True,nullable=False),sa.Column('reference',sa.String(128)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('deposit_requests',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('amount',sa.Numeric(20,4),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('reference',sa.String(160),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('orders',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('service_id',sa.Integer(),sa.ForeignKey('services.id'),nullable=False),sa.Column('quantity',sa.Integer(),nullable=False),sa.Column('total',sa.Numeric(20,4),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('idempotency_key',sa.String(128),unique=True,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint('quantity > 0'),sa.CheckConstraint('total >= 0'))
    op.create_table('audit_logs',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('actor_id',sa.Integer(),sa.ForeignKey('users.id')),sa.Column('action',sa.String(128),nullable=False),sa.Column('target',sa.String(128),nullable=False),sa.Column('metadata_json',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for t in ['audit_logs','orders','deposit_requests','wallet_transactions','wallets','services','categories','sessions','users']: op.drop_table(t)
