from alembic import op
import sqlalchemy as sa

revision='0002_production_subsystems'
down_revision='0001_initial'
branch_labels=None
depends_on=None


def upgrade():
    op.create_table('permissions', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('code',sa.String(100),unique=True,nullable=False))
    op.create_table('roles', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('name',sa.String(32),unique=True,nullable=False))
    op.create_table('user_roles', sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),primary_key=True), sa.Column('role_id',sa.Integer(),sa.ForeignKey('roles.id',ondelete='CASCADE'),primary_key=True))
    op.create_table('role_permissions', sa.Column('role_id',sa.Integer(),sa.ForeignKey('roles.id',ondelete='CASCADE'),primary_key=True), sa.Column('permission_id',sa.Integer(),sa.ForeignKey('permissions.id',ondelete='CASCADE'),primary_key=True))
    op.create_table('products', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('category_id',sa.Integer(),sa.ForeignKey('categories.id'),nullable=False), sa.Column('name',sa.String(200),nullable=False), sa.Column('slug',sa.String(200),unique=True,nullable=False), sa.Column('description',sa.Text(),nullable=False), sa.Column('enabled',sa.Boolean(),nullable=False), sa.Column('sort_order',sa.Integer(),nullable=False))
    op.create_table('pricing_rules', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('service_id',sa.Integer(),sa.ForeignKey('services.id',ondelete='CASCADE')), sa.Column('category_id',sa.Integer(),sa.ForeignKey('categories.id',ondelete='CASCADE')), sa.Column('provider_id',sa.Integer()), sa.Column('kind',sa.String(32),nullable=False), sa.Column('value',sa.Numeric(20,8),nullable=False), sa.Column('currency',sa.String(3)), sa.Column('priority',sa.Integer(),nullable=False), sa.Column('enabled',sa.Boolean(),nullable=False))
    op.create_table('providers', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('name',sa.String(120),unique=True,nullable=False), sa.Column('enabled',sa.Boolean(),nullable=False), sa.Column('priority',sa.Integer(),nullable=False), sa.Column('timeout_seconds',sa.Integer(),nullable=False), sa.Column('health_state',sa.String(32),nullable=False), sa.Column('config_key',sa.String(200)))
    op.create_table('provider_mappings', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('service_id',sa.Integer(),sa.ForeignKey('services.id',ondelete='CASCADE'),nullable=False), sa.Column('provider_id',sa.Integer(),sa.ForeignKey('providers.id',ondelete='CASCADE'),nullable=False), sa.Column('external_service_id',sa.String(128),nullable=False), sa.Column('priority',sa.Integer(),nullable=False), sa.Column('enabled',sa.Boolean(),nullable=False), sa.UniqueConstraint('service_id','provider_id','external_service_id'))
    op.create_table('provider_health', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('provider_id',sa.Integer(),sa.ForeignKey('providers.id',ondelete='CASCADE'),nullable=False), sa.Column('success_count',sa.Integer(),nullable=False), sa.Column('failure_count',sa.Integer(),nullable=False), sa.Column('consecutive_failures',sa.Integer(),nullable=False), sa.Column('last_error',sa.Text()), sa.Column('checked_at',sa.DateTime(timezone=True)))
    op.create_table('order_events', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('order_id',sa.Integer(),sa.ForeignKey('orders.id',ondelete='CASCADE'),nullable=False), sa.Column('old_status',sa.String(32)), sa.Column('new_status',sa.String(32),nullable=False), sa.Column('actor_id',sa.Integer(),sa.ForeignKey('users.id')), sa.Column('source',sa.String(32),nullable=False), sa.Column('metadata_json',sa.Text(),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('external_orders', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('order_id',sa.Integer(),sa.ForeignKey('orders.id',ondelete='CASCADE'),unique=True,nullable=False), sa.Column('provider_id',sa.Integer(),sa.ForeignKey('providers.id'),nullable=False), sa.Column('external_id',sa.String(160)), sa.Column('outcome',sa.String(32),nullable=False), sa.Column('request_fingerprint',sa.String(128),unique=True,nullable=False), sa.Column('last_checked_at',sa.DateTime(timezone=True)))
    op.create_table('payments', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False), sa.Column('provider',sa.String(80),nullable=False), sa.Column('external_id',sa.String(160),unique=True), sa.Column('amount',sa.Numeric(20,4),nullable=False), sa.Column('currency',sa.String(3),nullable=False), sa.Column('status',sa.String(32),nullable=False), sa.Column('idempotency_key',sa.String(128),unique=True,nullable=False), sa.Column('metadata_json',sa.Text(),nullable=False))
    op.create_table('coupons', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('code',sa.String(64),unique=True,nullable=False), sa.Column('kind',sa.String(16),nullable=False), sa.Column('value',sa.Numeric(20,4),nullable=False), sa.Column('min_order',sa.Numeric(20,4)), sa.Column('max_discount',sa.Numeric(20,4)), sa.Column('expires_at',sa.DateTime(timezone=True)), sa.Column('usage_limit',sa.Integer()), sa.Column('per_user_limit',sa.Integer(),nullable=False), sa.Column('active',sa.Boolean(),nullable=False))
    op.create_table('coupon_redemptions', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('coupon_id',sa.Integer(),sa.ForeignKey('coupons.id',ondelete='CASCADE'),nullable=False), sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False), sa.Column('order_id',sa.Integer(),sa.ForeignKey('orders.id')), sa.Column('discount',sa.Numeric(20,4),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('coupon_id','user_id','order_id'))
    op.create_table('notifications', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False), sa.Column('event',sa.String(64),nullable=False), sa.Column('payload_json',sa.Text(),nullable=False), sa.Column('status',sa.String(32),nullable=False), sa.Column('attempts',sa.Integer(),nullable=False), sa.Column('available_at',sa.DateTime(timezone=True),nullable=False), sa.Column('sent_at',sa.DateTime(timezone=True)))
    op.create_table('support_tickets', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False), sa.Column('assigned_to',sa.Integer(),sa.ForeignKey('users.id')), sa.Column('subject',sa.String(200),nullable=False), sa.Column('priority',sa.String(16),nullable=False), sa.Column('status',sa.String(32),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('support_messages', sa.Column('id',sa.Integer(),primary_key=True), sa.Column('ticket_id',sa.Integer(),sa.ForeignKey('support_tickets.id',ondelete='CASCADE'),nullable=False), sa.Column('sender_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False), sa.Column('body',sa.Text(),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('settings', sa.Column('key',sa.String(120),primary_key=True), sa.Column('value_json',sa.Text(),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_index('ix_services_enabled_category','services',['enabled','category_id'])
    op.create_index('ix_orders_user_created','orders',['user_id','created_at'])
    op.create_index('ix_notifications_status_available','notifications',['status','available_at'])


def downgrade():
    for t in ['settings','support_messages','support_tickets','notifications','coupon_redemptions','coupons','payments','external_orders','order_events','provider_health','provider_mappings','providers','pricing_rules','products','role_permissions','user_roles','roles','permissions']:
        op.drop_table(t)
